services:
  raporty-czytelnikow:
    build: .
    environment:
      USER_AGENT: ${USER_AGENT?}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN?}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID?}
    init: true
    restart: unless-stopped
